-- BUG-188: 첨부 blob 백업 폐기.
--
-- 0018 은 첨부를 index.db 에 통째로 복사해 "스냅샷만으로 첨부까지 복원" 을
-- 노렸다. 그런데 첨부는 크기 상한이 없는 유일한 데이터라 두 군데서 깨졌다:
--
--   1. SQLite blob 상한(약 1GB) — 1.5GB 파일 첨부가 `code 18: string or blob
--      too big` 으로 실패. 파일 write 는 이미 끝난 뒤라 참조 없는 대용량 파일이
--      남고, 그 뒤로는 reindex 의 self-heal 과 스냅샷이 계속 같은 에러로 실패.
--   2. 용량 — 첨부 하나가 index.db 와 매 스냅샷을 그 크기만큼 부풀린다.
--
-- admin 결정: 첨부는 백업 대상에서 제외한다(임계값을 두지 않고 아예 제외).
-- 파일은 그대로 `.guild/attachments/` 에 남고, 보관은 git 또는 사용자 몫이다.
-- 어드민 > 백업 화면에서 이 사실을 밝힌다.
--
-- index.db 는 파일에서 언제든 재생성되는 파생 캐시라 테이블 삭제가 안전하다.
-- (DROP 자체로는 파일이 줄지 않는다 — 공간은 다음 VACUUM 때 회수된다.)
DROP TABLE IF EXISTS attachment_blobs;
